// <auto-generated />
using System;
using InsureZen.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InsureZen.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InsureZen.Models.Claim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CheckerDecision")
                        .HasColumnType("text");

                    b.Property<Guid?>("CheckerId")
                        .HasColumnType("uuid");

                    b.Property<string>("CheckerNotes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CheckerReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ClaimAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ForwardedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("IncidentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InsuranceCompanyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MakerId")
                        .HasColumnType("uuid");

                    b.Property<string>("MakerNotes")
                        .HasColumnType("text");

                    b.Property<string>("MakerRecommendation")
                        .HasColumnType("text");

                    b.Property<DateTime?>("MakerReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PatientDob")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CheckerId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("InsuranceCompanyId");

                    b.HasIndex("MakerId");

                    b.HasIndex("Status");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("InsureZen.Models.InsuranceCompany", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("InsuranceCompanies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            ContactEmail = "claims@alphashield.com",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "AlphaShield Insurance"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            ContactEmail = "claims@betacare.com",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "BetaCare Health"
                        });
                });

            modelBuilder.Entity("InsureZen.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "alice@insurezen.com",
                            Name = "Alice Maker",
                            Role = "Maker"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "bob@insurezen.com",
                            Name = "Bob Maker",
                            Role = "Maker"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "carol@insurezen.com",
                            Name = "Carol Checker",
                            Role = "Checker"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "david@insurezen.com",
                            Name = "David Checker",
                            Role = "Checker"
                        });
                });

            modelBuilder.Entity("InsureZen.Models.Claim", b =>
                {
                    b.HasOne("InsureZen.Models.User", "Checker")
                        .WithMany("CheckerClaims")
                        .HasForeignKey("CheckerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InsureZen.Models.InsuranceCompany", "InsuranceCompany")
                        .WithMany("Claims")
                        .HasForeignKey("InsuranceCompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InsureZen.Models.User", "Maker")
                        .WithMany("MakerClaims")
                        .HasForeignKey("MakerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Checker");

                    b.Navigation("InsuranceCompany");

                    b.Navigation("Maker");
                });

            modelBuilder.Entity("InsureZen.Models.InsuranceCompany", b =>
                {
                    b.Navigation("Claims");
                });

            modelBuilder.Entity("InsureZen.Models.User", b =>
                {
                    b.Navigation("CheckerClaims");

                    b.Navigation("MakerClaims");
                });
#pragma warning restore 612, 618
        }
    }
}
